# Generated by Django 3.0.4 on 2020-04-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='facebook_url',
            field=models.URLField(null=True),
        ),
    ]
