# Generated by Django 3.0.4 on 2020-04-28 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0002_auto_20200429_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='facebook_url',
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
