# Generated by Django 3.0.4 on 2020-04-26 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0003_auto_20200427_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='district',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgApp.District'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgApp.City'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='thana',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orgApp.Thana'),
        ),
    ]
