# Generated by Django 3.0.4 on 2020-04-28 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0003_auto_20200429_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='organisation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='org_detail', serialize=False, to='orgApp.Organisation'),
        ),
    ]
