# Generated by Django 3.0.4 on 2020-04-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0004_auto_20200429_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgdetail',
            old_name='organisation',
            new_name='org',
        ),
    ]
