# Generated by Django 3.0.4 on 2020-04-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0005_auto_20200429_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='org',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='org_detail', serialize=False, to='orgApp.Organisation'),
        ),
    ]
