# Generated by Django 3.0.4 on 2020-04-28 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0007_auto_20200429_0347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgdetail',
            name='id',
        ),
        migrations.RemoveField(
            model_name='orgdetail',
            name='org',
        ),
        migrations.AddField(
            model_name='orgdetail',
            name='organiation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='org_detail', serialize=False, to='orgApp.Organisation'),
            preserve_default=False,
        ),
    ]
