# Generated by Django 3.0.4 on 2020-04-28 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0009_auto_20200429_0404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='organiation',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='org_detail', to='orgApp.Organisation'),
            preserve_default=False,
        ),
    ]
