# Generated by Django 3.0.4 on 2020-04-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0010_auto_20200429_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orgdetail',
            old_name='organiation',
            new_name='organisation',
        ),
    ]
