# Generated by Django 3.0.4 on 2020-04-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0011_auto_20200429_0438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgdetail',
            name='facebook_url',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/org'),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/logo'),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='twitter_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='website_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='orgdetail',
            name='youtube_url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='orgproject',
            name='project_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/org/project'),
        ),
    ]
