# Generated by Django 3.0.4 on 2020-04-29 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orgApp', '0013_auto_20200429_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
