# Generated by Django 3.0.4 on 2020-05-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgApp', '0014_auto_20200430_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
