# Generated by Django 3.0.4 on 2020-04-01 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of this post')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(max_length=300)),
                ('upload', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
