# Generated by Django 3.0.4 on 2020-04-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the title', max_length=200)),
                ('description', models.TextField(help_text='Enter a brief description of this post')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, max_length=2000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
            options={
                'get_latest_by': 'date',
            },
        ),
    ]
