# Generated by Django 3.0.4 on 2020-04-05 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corunaApp', '0004_auto_20200402_2329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'get_latest_by': 'date'},
        ),
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
